controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: -0.2
  max_rotational_vel: 0.2 # 0.04
  max_vel_theta: 0.8
  min_in_place_rotational_vel: 0.01

  acc_lim_th: 3.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false
  
  yaw_goal_tolerance: 0.2 # about 12 degrees
  xy_goal_tolerance: 0.2 # 20 cm
  
  heading_lookahead: 0.3
  heading_scoring: false
  heading_scoring_timestep: 0.1
  meter_scoring: true
  oscillation_reset_dist: 0.05
  occdist_scale: 0.05
  
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 20
  dwa: true
  simple_attractor: false
