map_type: costmap


transform_tolerance: 0.4
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 1.0
footprint: [[0.3,0.3],[-0.3,0.3],[-0.3,-0.3],[0.3,-0.3]]


observation_sources: velodyne_scan hokuyo_scan

velodyne_scan: {sensor_frame: velodyne_link, topic: /velodyne/scan, data_type: LaserScan, marking: true, clearing: false}
hokuyo_scan: {sensor_frame: hokuyo_link, topic: /scan, data_type: LaserScan, marking: true, clearing: true}
