map_type: costmap


transform_tolerance: 0.4
obstacle_range: 5.5
raytrace_range: 6.0
inflation_radius: 0.5
footprint: [[0.3,0.3],[-0.3,0.3],[-0.3,-0.3],[0.3,-0.3]]


#observation_sources: velodyne_scan hokuyo_scan
observation_sources: velodyne_scan

velodyne_scan: {sensor_frame: velodyne, topic: /velodyne/scan, data_type: LaserScan, marking: true, clearing: true}
hokuyo_scan: {sensor_frame: hokuyo_link, topic: /scan, data_type: LaserScan, marking: true, clearing: true}
