TrajectoryPlannerROS: {acc_lim_th: 3.0, acc_lim_x: 2.5, acc_lim_y: 2.5, angular_sim_granularity: 0.025,
  dwa: true, heading_lookahead: 0.3, heading_scoring: false, heading_scoring_timestep: 0.1,
  holonomic_robot: false, max_rotational_vel: 0.2, max_vel_theta: 0.8, max_vel_x: 0.2,
  meter_scoring: true, min_in_place_rotational_vel: 0.01, min_vel_x: -0.2, occdist_scale: 0.05,
  oscillation_reset_dist: 0.05, sim_granularity: 0.025, sim_time: 1.7, simple_attractor: false,
  vtheta_samples: 20, vx_samples: 8, xy_goal_tolerance: 0.2, yaw_goal_tolerance: 0.2}
  
clearing_rotation_allowed: true
controller_frequency: 10

global_costmap:
  footprint:
  - [0.3, 0.3]
  - [-0.3, 0.3]
  - [-0.3, -0.3]
  - [0.3, -0.3]
  global_frame: odom
  height: 12.0
  hokuyo_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: hokuyo_link,
    topic: /scan}
  inflation_radius: 0.5
  map_type: costmap
  observation_sources: velodyne_scan
  obstacle_range: 5.5
  origin_x: 0.0
  origin_y: 0.0
  publish_frequency: 1.0
  raytrace_range: 6.0
  resolution: 0.1
  robot_base_frame: base_footprint
  rolling_window: true
  static_map: false
  transform_tolerance: 0.4
  update_frequency: 5.0
  velodyne_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: velodyne,
    topic: /velodyne/scan}
  width: 12.0
local_costmap:
  footprint:
  - [0.3, 0.3]
  - [-0.3, 0.3]
  - [-0.3, -0.3]
  - [0.3, -0.3]
  global_frame: odom
  height: 12.0
  hokuyo_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: hokuyo_link,
    topic: /scan}
  velodyne_scan: {clearing: true, data_type: LaserScan, marking: true, sensor_frame: velodyne,
    topic: /velodyne/scan}
  inflation_radius: 0.5
  map_type: costmap
  observation_sources: velodyne_scan
  obstacle_range: 5.5
  origin_x: 0.0
  origin_y: 0.0
  publish_frequency: 1.0
  raytrace_range: 6.0
  resolution: 0.05
  robot_base_frame: base_footprint
  rolling_window: true
  static_map: false
  transform_tolerance: 0.4
  update_frequency: 5.0
  width: 20.0
  
  plugins:
   - {name: traversability, type: rt_traversability_layer/TraversabilityLayer}
   
   #traversability:
   
   
  
recovery_behavior_enabled: true

