footprint: [[0.4, 0.3], [-0.4, 0.3], [-0.4, -0.3], [0.4, -0.3]]

planner_patience: 2.5 # How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.

controller_frequency: 5.0
controller_patience: 10.0
clearing_radius: 0.59
footprint_padding: 0.015
oscillation_timeout: 10.0
oscillation_distance: 0.5
