 # 0 - off
 # 2 - auto
 # 3 - manual

video_mode: 640x480_rgb8
#video_mode: 320x240_yuv422
frame_rate: 7.5
#frame_rate: 3.75
iso_speed: 400

auto_gain: 2
auto_exposure: 2 # Combined Gain, Iris & Shutter control
auto_brightness: 2
auto_gamma: 2           # 3 - Manual
gamma: 2 # was 2
auto_shutter: 2         # Auto
auto_white_balance: 2   # Auto
